
# sample.txt
try is a inbuilt function for exception handling
in this program we have opened filea(sample.txt) and assgined to variable a
. to read a we used the function.read to and assginded to fileread
after that we have the close the file.
for exception handling we used the filenotfounderror


# output.txt
in this program we have two inputs which are a,b in first set of code we take a as input and write in the output.txt file.
and next set of code we write the b input and place it in output.txt for the final set of code we read the file output.txt file and print in the final_reading.
