
# sample.txt
try is a inbuilt function for exception handling
in this program we have opened filea(sample.txt) and assgined to variable a
. to read a we used the function.read to and assginded to fileread
after that we have the close the file.
for exception handling we used the filenotfounderror
